services:
  claroline.listener.rssreader_widget:
    class: Claroline\RssReaderBundle\Listener\RssReaderListener
    calls:
      - [setContainer, ["@service_container"]]
    tags:
      - { name: kernel.event_listener, event: widget_claroline_rssreader_workspace, method: onWorkspaceDisplay }
      - { name: kernel.event_listener, event: widget_claroline_rssreader_desktop, method: onDesktopDisplay }
      - { name: kernel.event_listener, event: widget_claroline_rssreader_configuration_workspace, method: onWorkspaceConfigure }
      - { name: kernel.event_listener, event: widget_claroline_rssreader_configuration_desktop, method: onDesktopConfigure }
      - { name: kernel.event_listener, event: widget_claroline_rssreader_to_template, method: onExportConfig }
      - { name: kernel.event_listener, event: widget_claroline_rssreader_from_template, method: onImportConfig }